import os
import json
import uuid
import math
import string
import re
from datetime import datetime, timezone
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
groq_client = Groq(api_key=GROQ_API_KEY)

AUDIT_LOG_FILE = "audit_log.json"

# ── Thresholds ────────────────────────────────────────────────────────────────
THRESHOLD_AI     = 0.70   # above this → likely_ai
THRESHOLD_HUMAN  = 0.40   # below this → likely_human
# between → uncertain


# ── Audit log helpers ─────────────────────────────────────────────────────────

def _read_log():
    if not os.path.exists(AUDIT_LOG_FILE):
        return []
    with open(AUDIT_LOG_FILE, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []


def _write_log(entries):
    with open(AUDIT_LOG_FILE, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)


def _append_entry(entry):
    entries = _read_log()
    entries.append(entry)
    _write_log(entries)


def _now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"


# ── Signal 1: LLM-based classifier (Groq) ────────────────────────────────────

def classify_with_llm(text: str) -> float:
    """
    Ask Groq's llama-3.3-70b-versatile to estimate the probability that
    the text is AI-generated. Returns a float in [0.0, 1.0].
    1.0 = certainly AI-generated.
    Falls back to 0.5 on any API or parse error.
    """
    prompt = f"""You are an expert classifier that detects whether text was written by a human or generated by an AI writing tool.

Analyze the following text carefully. Look for:
- Unnaturally consistent sentence structure and length
- Hedged corporate/academic phrasing ("it is important to note", "furthermore", "it is worth mentioning")
- Absence of personal voice, typos, or idiosyncratic detours
- Perfectly balanced paragraph structures
- Overuse of transitional phrases
- Generic, non-specific examples and observations

Respond with ONLY a JSON object in this exact format, no other text:
{{"ai_probability": <float between 0.0 and 1.0>}}

Where 1.0 means you are certain the text is AI-generated and 0.0 means you are certain it is human-written.

TEXT TO ANALYZE:
\"\"\"
{text}
\"\"\"
"""
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=50,
        )
        raw = response.choices[0].message.content.strip()
        # Extract the JSON object even if the model adds minor surrounding text
        match = re.search(r'\{.*?"ai_probability"\s*:\s*([0-9.]+).*?\}', raw, re.DOTALL)
        if match:
            score = float(match.group(1))
            return max(0.0, min(1.0, score))
        return 0.5
    except Exception:
        return 0.5


# ── Signal 2: Stylometric heuristics ─────────────────────────────────────────

def _sentence_length_variance(text: str) -> float:
    """
    Computes the coefficient of variation of sentence word-counts.
    High variance → more human-like → lower AI score.
    Returns a normalized AI-likelihood score in [0.0, 1.0].
    """
    # Split on sentence-ending punctuation
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.5  # can't compute variance on single sentence
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    if mean_len == 0:
        return 0.5
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    cv = math.sqrt(variance) / mean_len  # coefficient of variation
    # High CV means irregular (human). Low CV means uniform (AI).
    # Clamp CV to [0, 2.0] and invert for AI score.
    cv_clamped = min(cv, 2.0)
    ai_score = 1.0 - (cv_clamped / 2.0)
    return ai_score


def _type_token_ratio(text: str) -> float:
    """
    Ratio of unique word types to total tokens.
    Very high TTR in formal text suggests AI; very low TTR suggests repetitive AI.
    Human casual text tends toward mid-range TTR.
    We treat extremes (>0.85 or <0.30) as AI-like.
    Returns an AI-likelihood score in [0.0, 1.0].
    """
    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5
    ttr = len(set(words)) / len(words)
    # Map to AI likelihood: extremes are AI-like, mid-range is human-like
    # Using a V-shape: minimum AI-likelihood at ttr≈0.6
    distance_from_human = abs(ttr - 0.60)
    ai_score = min(distance_from_human / 0.40, 1.0)
    return ai_score


def _punctuation_density(text: str) -> float:
    """
    AI text uses clean, standard punctuation (periods, commas) and avoids
    ellipses, em-dashes, exclamation marks, and unconventional patterns.
    Low punctuation diversity → more AI-like.
    Returns an AI-likelihood score in [0.0, 1.0].
    """
    if not text:
        return 0.5
    # Count distinct punctuation characters used
    puncts_used = set(ch for ch in text if ch in string.punctuation)
    # Standard punctuation only (AI tends to use just . , : ; ?)
    standard_puncts = set('.,:;?')
    unusual_puncts = puncts_used - standard_puncts
    # More unusual punctuation → more human
    unusual_ratio = len(unusual_puncts) / max(len(puncts_used), 1)
    ai_score = 1.0 - unusual_ratio
    return ai_score


def classify_with_stylometrics(text: str) -> float:
    """
    Combines three stylometric sub-signals (sentence length variance,
    type-token ratio, punctuation density) into a single score in [0.0, 1.0].
    1.0 = structurally AI-like.
    """
    slv_score  = _sentence_length_variance(text)
    ttr_score  = _type_token_ratio(text)
    punct_score = _punctuation_density(text)
    # Equal weights across all three sub-metrics
    return round((slv_score + ttr_score + punct_score) / 3.0, 4)


# ── Confidence scorer ─────────────────────────────────────────────────────────

def compute_confidence(llm_score: float, stylo_score: float) -> tuple[float, str]:
    """
    Combines both signals into a calibrated confidence score and attribution.
    LLM is weighted 60%, stylometrics 40%.
    Returns (combined_score, attribution_label).
    """
    combined = round(0.6 * llm_score + 0.4 * stylo_score, 4)
    if combined > THRESHOLD_AI:
        attribution = "likely_ai"
    elif combined < THRESHOLD_HUMAN:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    return combined, attribution


# ── Transparency label generator ──────────────────────────────────────────────

def generate_label(attribution: str, confidence: float) -> str:
    """
    Maps an attribution result and combined confidence score to the
    exact transparency label text displayed to end users.
    """
    if attribution == "likely_ai":
        pct = round(confidence * 100)
        return (
            f"⚠️ Likely AI-Generated — Our analysis suggests this content was probably "
            f"created using an AI writing tool (confidence: {pct}%). "
            f"If you believe this is incorrect, the creator can submit an appeal."
        )
    elif attribution == "likely_human":
        human_pct = round((1.0 - confidence) * 100)
        return (
            f"✓ Likely Human-Written — Our analysis suggests this content was written by a person "
            f"(confidence: {human_pct}% human). "
            f"Attribution is based on automated analysis and may not be perfect."
        )
    else:  # uncertain
        pct = round(confidence * 100)
        return (
            f"\U0001f50d Attribution Unclear — We couldn’t confidently determine whether this content "
            f"was written by a person or an AI tool (confidence: {pct}%). "
            f"The result is inconclusive; treat it with appropriate skepticism."
        )


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400
    text = data.get("text", "").strip()
    creator_id = data.get("creator_id", "").strip()
    if not text:
        return jsonify({"error": "Field 'text' is required and must not be empty."}), 400
    if not creator_id:
        return jsonify({"error": "Field 'creator_id' is required."}), 400

    content_id = str(uuid.uuid4())
    timestamp  = _now_iso()

    llm_score   = classify_with_llm(text)
    stylo_score = classify_with_stylometrics(text)
    confidence, attribution = compute_confidence(llm_score, stylo_score)
    label = generate_label(attribution, confidence)

    log_entry = {
        "event":       "classification",
        "content_id":  content_id,
        "creator_id":  creator_id,
        "timestamp":   timestamp,
        "attribution": attribution,
        "confidence":  confidence,
        "llm_score":   round(llm_score, 4),
        "stylo_score": round(stylo_score, 4),
        "label":       label,
        "status":      "classified",
        "text_preview": text[:120] + ("..." if len(text) > 120 else ""),
    }
    _append_entry(log_entry)

    return jsonify({
        "content_id":  content_id,
        "attribution": attribution,
        "confidence":  confidence,
        "llm_score":   round(llm_score, 4),
        "stylo_score": round(stylo_score, 4),
        "label":       label,
        "status":      "classified",
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400
    content_id = data.get("content_id", "").strip()
    reasoning  = data.get("creator_reasoning", "").strip()
    if not content_id:
        return jsonify({"error": "Field 'content_id' is required."}), 400
    if not reasoning:
        return jsonify({"error": "Field 'creator_reasoning' is required."}), 400

    entries = _read_log()
    found = False
    for entry in entries:
        if entry.get("content_id") == content_id and entry.get("event") == "classification":
            entry["status"] = "under_review"
            found = True
            break

    if not found:
        return jsonify({"error": f"No submission found for content_id '{content_id}'."}), 404

    appeal_entry = {
        "event":             "appeal",
        "content_id":        content_id,
        "timestamp":         _now_iso(),
        "appeal_reasoning":  reasoning,
        "status":            "under_review",
    }
    entries.append(appeal_entry)
    _write_log(entries)

    return jsonify({
        "status":     "appeal_received",
        "content_id": content_id,
        "message":    (
            "Your appeal has been logged and the content is now marked as 'under review'. "
            "A human reviewer will examine the original classification and your reasoning."
        ),
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    entries = _read_log()
    limit = request.args.get("limit", 50, type=int)
    return jsonify({
        "total":   len(entries),
        "entries": entries[-limit:],
    }), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok"}), 200


if __name__ == "__main__":
    app.run(debug=True)
